package com.test;
 
import java.util.List;
import java.lang.Long;
import org.drools.runtime.process.WorkflowProcessInstance;
import java.util.Map;
import java.util.HashMap;

rule "Exceeds" 
        ruleflow-group "ExceedsGroup"
	
	
	when
		$process: WorkflowProcessInstance()
		eval( ((Long)$process.getVariable("accuralCount")).longValue() > ((Long)$process.getVariable("limit")).longValue() )
	then
		((WorkflowProcessInstance)kcontext.getKnowledgeRuntime().getProcessInstance($process.getId())).setVariable("exceeds", true);
end

rule "NotExceeds" 
        ruleflow-group "ExceedsGroup"
	
	
	when
		$process: WorkflowProcessInstance()
                eval( ((Long)$process.getVariable("accuralCount")).longValue() < ((Long)$process.getVariable("limit")).longValue() )
	then
		((WorkflowProcessInstance)kcontext.getKnowledgeRuntime().getProcessInstance($process.getId())).setVariable("exceeds", false);
end